[package]
    authors = [
        "u3l6",
    ]
    description = "AppPorter"
    edition = "2021"
    name = "app-porter"
    version = "0.1.0"

    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
    # The `_lib` suffix may seem redundant but it is necessary
    # to make the lib name unique and wouldn't conflict with the bin name.
    # This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
    crate-type = [
        "cdylib",
        "rlib",
        "staticlib",
    ]
    name = "app_porter_lib"

[build-dependencies]
    tauri-build = { version = "2.0.5", features = [
    ] }

[dependencies]
    serde = { version = "1.0.217", features = [
        "derive",
    ] }
    serde_json = "1.0.138"
    tauri = { version = "2.2.5", features = [
        "tray-icon",
    ] }
    tauri-plugin-opener = "2.2.5"

    base64 = "0.22.1"
    check_elevation = "0.2.4"
    config = "0.15.7"
    dirs = "6.0.0"
    mslnk = "0.1.8"
    systemicons = "0.9.13"
    tauri-plugin-clipboard-manager = "2.2.1"
    tauri-plugin-dialog = "2.2.0"
    tauri-plugin-fs = "2.2.0"
    tauri-plugin-process = "2.2.0"
    tempfile = "3.16.0"
    toml = "0.8.19"
    windows-registry = "0.4.0"
    zip = "2.2.2"
