download_dir = ''
language = 'en'
minimize_to_tray_on_close = false
system_drive_letter = 'C'
theme = 'system'
username = 'Administrator'
[installation]
    install_mode = 'AllUsers'
    start_path = ''
    zip_path = ''
    [installation.all_users]
        create_desktop_shortcut = false
        create_registry_key = true
        create_start_menu_shortcut = true
        install_path = ''
    [installation.current_user]
        create_desktop_shortcut = false
        create_registry_key = true
        create_start_menu_shortcut = true
        install_path = ''
