// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppDetails } from "./AppDetails";
import type { AppValidationStatus } from "./AppValidationStatus";

export type App = { timestamp: bigint, installed: boolean, url: string, archive_password: string, details: AppDetails, validation_status: AppValidationStatus, };
