// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { custom_icon: boolean, create_desktop_shortcut: boolean, create_start_menu_shortcut: boolean, create_registry_key: boolean, add_to_path: [boolean, string], };
