// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfig } from "./AppConfig";
import type { AppInfo } from "./AppInfo";

export type AppDetails = { current_user_only: boolean, info: AppInfo, config: AppConfig, install_path: string, full_path: string, };
