// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallSettings } from "./InstallSettings";

export type AppInstall = { current_user_only: boolean, all_users: InstallSettings, current_user: InstallSettings, };
