// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { App } from "./App";

export type AppInstallConfig = { app: App, archive_exe_path: string, archive_path_dir: string, zip_path: string, };
