// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Env = { debug: boolean, elevated: boolean, system_drive_letter: string, user_sid: string, username: string, };
