// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExeDetails = { product_name: string, version: string, copyright: string, icon_data_url: string, };
