// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTreeNode = { key: string, name: string, path: string, node_type: string, children: Array<FileTreeNode> | null, expanded: boolean, level: number, };
