// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { App } from "./App";
import type { Tool } from "./Tool";
import type { Url } from "./Url";

export type Library = { apps: Array<App>, tools: Array<Tool>, urls: Array<Url>, };
