// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppInstall } from "./AppInstall";
import type { LanguageType } from "./LanguageType";
import type { ThemeType } from "./ThemeType";
import type { ToolInstall } from "./ToolInstall";

export type Settings = { first_run: boolean, language: LanguageType, theme: ThemeType, minimize_to_tray_on_close: boolean, context_menu: boolean, auto_startup: boolean, color: string, run_as_admin: boolean, app_install: AppInstall, tool_install: ToolInstall, };
