// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDetails } from "./ToolDetails";
import type { ToolValidationStatus } from "./ToolValidationStatus";

export type Tool = { id: string, timestamp_add: string, timestamp_update: string, installed: boolean, url: string, archive_password: string, details: ToolDetails, validation_status: ToolValidationStatus, };
