// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDetails } from "./ToolDetails";
import type { ToolValidationStatus } from "./ToolValidationStatus";

export type Tool = { timestamp: bigint, installed: boolean, url: string, archive_password: string, details: ToolDetails, validation_status: ToolValidationStatus, };
