// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";

export type ToolInstallConfig = { tool: Tool, archive_path_dir: string, zip_path: string, };
