name: udeps

on: 
  push:
  pull_request:

jobs:
  udeps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-udeps
        run: cargo install cargo-udeps --locked

      - name: Run Udeps
        run: |
          cd src-tauri
          cargo udeps --all-targets --all-features
